title: steakscience
description: "A blog about technology, design, and culture. Probably off-topic. Written by Nirawit Jittipairoj."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://steakscience.com" # the base hostname & protocol for your site

#Information that is used to create the Terms of Service & Privacy Policy pages
# company: Company Name
# location: Location
# start-year: 2016

# Build settings
markdown: kramdown
# markdown: CommonMark
exclude: [node_modules, package.json, gulpfile.js, README.md, vendor, Gemfile, Gemfile.lock, LICENSE, Rakefile]
include: [_pages, .nojekyll]
permalink: /:title/

plugins:
    # - jekyll-minifier
    # - octopress-minify-html
    - jekyll-figure
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-analytics
    - jekyll-feed
    - jekyll-typogrify
    - jekyll-autoprefixer
    # - s3_website
    # - jekyll-hyphenate-filter

autoprefixer:
  only_production: true

sass:
  style: compressed

jekyll_analytics: 
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-61560416-2       # Required - replace with your tracking id
    anonymizeIp: true   