# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'images/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Author', name: 'author', widget: 'hidden', default: 'Nirawit Jittipairoj' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', timeFormat: 'false' }
      - { label: 'Category', name: 'categories', widget: 'string' }
      - { label: 'Hero Image', name: 'image', widget: 'image', allow_multiple: 'false' }
      - { label: 'Hero Video', name: 'hero_vid', widget: 'file', allow_multiple: 'false' }
      - { label: 'Body', name: 'body', widget: 'markdown' }